easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        - App\Entity\Stage
        - App\Entity\Formation
        - App\Entity\Entreprise
        - App\Entity\User
